---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - name: grpc-server
        image: 3bittechs/k8s-grpc-server:1.0
        ports:
        - containerPort: 8888
        readinessProbe:
          exec:
            command: ["/grpc_health_probe", "-addr=:8888"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/grpc_health_probe", "-addr=:8888"]
          initialDelaySeconds: 10        
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server
  namespace: default
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: grpc-server
  sessionAffinity: None
  type: ClusterIP
